### ISSUE TITLE
Use the public Casper API

### ISSUE THREAD

**Issue by Autarc** [fisch0920/snapchat#2]
Since the API defined at [https://api.casper.io/](https://api.casper.io) got public endpoints for the security calls which supports SSL/HTTPS in contrast the former service, it could be usefull to switch. Unfortunately even after updating the digest to the latest version (9.14.2) the generated signature doesn't seem to match.

**Comment by fisch0920** [comment]
Master is working for me with v9.14.0.

We definitely need to update the client auth token call to use casper's SSL endpoint; should get to this sometime this week, but feel free to send a PR beforehand :)

**Comment by fisch0920** [comment]
snapchat@2.0.1 has been updated to use casper's SSL attestation and auth token endpoints.  It's also available on npm now under the `snapchat` package.
