### ISSUE TITLE
Google Auth is not working

### ISSUE THREAD

**Issue by 700ghz** [fisch0920/snapchat#27]
I get `Error: Snapchat._getGoogleAuthToken unknown error`. 
But main problem is google auth error. At 816 line of index.js we have result of response from 'https://android.clients.google.com/auth'. Body of response has "Error=BadAuthentication", but login and password are correctly (100%).

Also I have tried:
https://accounts.google.com/DisplayUnlockCaptcha
https://www.google.com/settings/security/lesssecureapps
But it does not help.

**Comment by liamzebedee** [comment]
Same here

**Comment by VirenMohindra** [comment]
same, is this api deprecated?

**Comment by fisch0920** [comment]
Just added an updated Status to the README to let people know up front that this library is currently broken. Sorry for any confusion.
