### ISSUE TITLE
Library broken (DroidGuard service down)

### ISSUE THREAD

**Issue by Rob--** [fisch0920/snapchat#29]
I was messing around with the Snapchat app and this library a bit to see why #27 the Google Auth token couldn't be retrieved. I see multiple calls made to `https://android.clients.google.com/auth`, but in all the requests the app header is `com.google.android.gms` and the parameter for the `callerPkg` is `com.google.android.gms` too. I see no requests made to the `auth` endpoint with the Snapchat package name during login, logout and general usage of the app so from this I assume that the Snapchat app is not making any calls to the `auth` endpoint.

So I tried editing the library to work without the need of a Google Auth token (as it seems the Snapchat android app can work without requesting it). I then ran into another issue. The login request takes a parameter called `attestation`, and this library retrieves that value through the Casper API. But the problem is these endpoints are no longer active.

Both of these endpoints return not found:
https://api.casper.io/droidguard/create/binary
https://api.casper.io/droidguard/attest/binary

```
{
    "code": 404,
    "message": "The DroidGuard Service is no longer available."
}
```

I'm not sure how the Snapchat android app generates the `attestation` value, this will require decompiling the app which I've not looked into.

I've not looked any further than this. It does seem possible to reissue the login request hours later and it works fine. So it may be possible to reuse the attestation value after manually receiving it once?

**Comment by jsutaria** [comment]
@fisch0920 is there any chance of this being resolved soon? I am having the google auth issues as well.

**Comment by fisch0920** [comment]
hey @jsutaria, i'm honestly not sure what it would take to get this lib working again as I haven't had time to look at this project in awhile.  maybe another contributor on here knows how to help you move forward.

**Comment by jsutaria** [comment]
@fisch0920 is it possible to use an older version of the api that was working or something like that?

**Comment by fisch0920** [comment]
Unfortunately, Snapchat disallows accessing previous versions so as far as I know it's currently a no-go.  I'd suggest checking out the php lib for people who may know more: https://github.com/mgp25/SC-API/

**Comment by jsutaria** [comment]
Thanks!

**Comment by fisch0920** [comment]
Just added an updated Status to the README to let people know up front that this library is currently broken.  Sorry for any confusion.
